//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppManager()
        {
            this.EbamApps = new HashSet<EbamApp>();
            this.EbamSupports = new HashSet<EbamSupport>();
            this.EbamSupports1 = new HashSet<EbamSupport>();
            this.EbamWorklifeBals = new HashSet<EbamWorklifeBal>();
            this.LeaveEbamLists = new HashSet<LeaveEbamList>();
            this.LeaveEbams = new HashSet<LeaveEbam>();
            this.LeaveEbams1 = new HashSet<LeaveEbam>();
        }
    
        public int Id { get; set; }
        public string Manager { get; set; }
        public Nullable<int> SupportId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbamApp> EbamApps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbamSupport> EbamSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbamSupport> EbamSupports1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbamWorklifeBal> EbamWorklifeBals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEbamList> LeaveEbamLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEbam> LeaveEbams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveEbam> LeaveEbams1 { get; set; }
    }
}
