//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbamApp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EbamApp()
        {
            this.EbamSupportFiles = new HashSet<EbamSupportFile>();
        }
    
        public int Id { get; set; }
        public string AppName { get; set; }
        public string Usage { get; set; }
        public string Host_IP { get; set; }
        public string Public_IP { get; set; }
        public string DB_name { get; set; }
        public string DB_IP { get; set; }
        public string DB_Type { get; set; }
        public string DB_user { get; set; }
        public string Server_name { get; set; }
        public string Type { get; set; }
        public string OS_Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> SupportId { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual AppManager AppManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EbamSupportFile> EbamSupportFiles { get; set; }
    }
}
