//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbamSupport
    {
        public int Id { get; set; }
        public Nullable<int> SupportId { get; set; }
        public Nullable<int> SupportId2 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string Duration { get; set; }
        public Nullable<System.DateTime> StateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual AppManager AppManager { get; set; }
        public virtual AppManager AppManager1 { get; set; }
    }
}
