//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ebam_App_dbEntities : DbContext
    {
        public Ebam_App_dbEntities()
            : base("name=Ebam_App_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppManager> AppManagers { get; set; }
        public virtual DbSet<EbamApp> EbamApps { get; set; }
        public virtual DbSet<EbamSupportFile> EbamSupportFiles { get; set; }
        public virtual DbSet<EbamSupport> EbamSupports { get; set; }
        public virtual DbSet<EbamWorklifeBal> EbamWorklifeBals { get; set; }
        public virtual DbSet<LeaveEbamList> LeaveEbamLists { get; set; }
        public virtual DbSet<LeaveEbam> LeaveEbams { get; set; }
    }
}
