//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbamSupportFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<int> FileId { get; set; }
    
        public virtual EbamApp EbamApp { get; set; }
    }
}
