//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbamWorklifeBal
    {
        public int Id { get; set; }
        public Nullable<int> SupportId { get; set; }
        public Nullable<System.DateTime> BalDate { get; set; }
        public string Status { get; set; }
    
        public virtual AppManager AppManager { get; set; }
    }
}
