//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveEbam
    {
        public int id { get; set; }
        public Nullable<int> SupportId { get; set; }
        public Nullable<int> SupportId2 { get; set; }
        public Nullable<int> OutstandLeave { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<int> RemainDays { get; set; }
        public string BackUpStaff { get; set; }
    
        public virtual AppManager AppManager { get; set; }
        public virtual AppManager AppManager1 { get; set; }
    }
}
